esphome:
  name: nibe-bridge-pico
  friendly_name: Nibe Bridge Pico
packages:
  base: !include packages/base.yaml
  hw: !include packages/pico_w_base.yaml
external_components:
  - source:
      type: local
      path: components
